### ISSUE TITLE
NSpy 다운로드에 관해서 질문이 있습니다.

### ISSUE THREAD

**Issue by queenlovenaver** [d3xter-lab/NSpy#1]
안녕하세요 NSpy 개발자님.

저는 프리패스 플러그인을 잘 쓰고 있었던 네이버 유저입니다.

우연히 이틀 전에, @petekim123님께서 4월달에 네이버 카페 프리패스 개발자님께 문의한 글을 보고
NSpy 개발자님께서 @petekim123님께 쓴 답글을 보았습니다.
그래서 개발자님의 답글을 보고
프리패스를 다시 쓸 수도 있겠다는 희망이 생겨 NSpy를 다운로드 하다가,
프로그램 실행에 문제가 생겨서 질문을 드렸습니다.

개발자님께서 쓰신 다운로드 매뉴얼처럼 크롬의 익스텐션
홈페이지에서 developer mode를 활성화하는 건
성공했습니다.
근데 load unpacked로 로드하는 과정에서,
Nspy Code Download zip을 다운로드하고 압축해제까지
한 뒤에 Nspy-main 파일로 로드를 하려 하면
매니페스트 파일이 없거나 읽을 수 없다고 오류가 나옵니다.

그래서 매니페스트 파일은 뭔지,
또 다운로드 매뉴얼에서 레포지토리를 clone하는 방법이나 
소스코드를 직접 다운로드하는 방법은 어떻게 하는 것인지 
전혀 몰라 질문을 드렸습니다.

프리패스를 역사와 민속학 공부로 인한 자료조사용으로 유용하게 쓴 만큼
다시 이용하고 싶어,
간절한 마음으로 개발자님께 글을 썼습니다.
글 읽어주셔서 진심으로 감사드립니다.

**Comment by d3xter-lab** [comment]
@queenlovenaver 안녕하세요. zip파일로 다운로드 받으셨으면 원하시는 위치에 압축을 해제하신 이후 크롬에서 'load unpacked' 시에 src 디렉토리를 지정해주셔야합니다. src 디렉토리 안에 소스코드가 있는 구조라 해당 위치를 지정해주시면 정상적으로 로드될거에요!

**Comment by queenlovenaver** [comment]
> @queenlovenaver 안녕하세요. zip파일로 다운로드 받으셨으면 원하시는 위치에 압축을 해제하신 이후 크롬에서 'load unpacked' 시에 src 디렉토리를 지정해주셔야합니다. src 디렉토리 안에 소스코드가 있는 구조라 해당 위치를 지정해주시면 정상적으로 로드될거에요!

안녕하세요. 개발자님. 개발자님이 써주신대로 하니 크롬에 NSpy를 로드하는 것을 성공했습니다. 정말 감사드립니다.
NSpy를 써보았는데요. 몇몇 카페글들은 예전엔 못 보다가 NSpy를 통해 볼 수 있는 글들이 있었고,
몇몇 카페글들은 아직도 네이버 아이디로 로그인을 하고 봐야 한다고 알림이 떴습니다.
왜일까 하다가 개발자님의 NSpy 설명 글을 뒤 늦게 봤는데요.

'네이버에서 검색되는 것을 허용한 게시글에만 동작합니다.' 라고 써져 있더라구요.

그래서 개발자님 글대로라면 카페 글을 작성하신 분이 본인 글에 네이버 검색을 허용 안 한다고 설정했으면,
그 글은 NSpy를 켜도 못 본다는 것인데, 제가 제대로 이해한 게 맞나요?

번거로우실텐데 이 글도 봐주셔서 깊이 감사드립니다.

**Comment by d3xter-lab** [comment]
네 맞습니다. 카페 내 글쓰기 페이지에 보면 검색허용하는 옵션이 있습니다. 기본적으로 허용이 체크되어있어서 작성자가 해제하지 않으면 해당 글은 검색이 되게 되어있습니다. 다만 작성자가 해당 옵션을 해제하면 그 글은 네이버 로그인 및 해당 카페의 권한에 따라 보기가 가능하게 됩니다.

설명에 있는대로 개인적인 용도로 만들어진 확장 프로그램이라 버그가 있을 수 있습니다. 에러만 봐서는 알수가 없어서.. 가능하시면 해당 링크를 공유해주시면 확인해보겠습니다.

**Comment by queenlovenaver** [comment]
> 네 맞습니다. 카페 내 글쓰기 페이지에 보면 검색허용하는 옵션이 있습니다. 기본적으로 허용이 체크되어있어서 작성자가 해제하지 않으면 해당 글은 검색이 되게 되어있습니다. 다만 작성자가 해당 옵션을 해제하면 그 글은 네이버 로그인 및 해당 카페의 권한에 따라 보기가 가능하게 됩니다.
> 
> 설명에 있는대로 개인적인 용도로 만들어진 확장 프로그램이라 버그가 있을 수 있습니다. 에러만 봐서는 알수가 없어서.. 가능하시면 해당 링크를 공유해주시면 확인해보겠습니다.

아.. 그렇군요. 그래서 네이버 검색창에
'00' 에 대한 검색결과가 없습니다.
라고 뜨는 카페글은 볼 수가 없는 거군요
ㅠ..

제가 못 봤던 카페글은 민속학 카페의 '서술시험 키워드 학습법 ^^' 이라는 글이었는데요.
개발자님 쓰신 글처럼 카페 작성자님이
검색을 비허용하신 것 같아요.
개발자님께서 링크를 공유해달라 하셔서 링크 공유하겠습니다.
https://cafe.naver.com/folkloristic?iframe_url_utf8=%2FArticleRead.nhn%253Fclubid%3D30474655%2526menuid%3D22%2526boardtype%3DC%2526page%3D1%2526articleid%3D257%2526referrerAllArticles%3Dfalse

다시 한 번 글 봐주셔서 감사드립니다.

**Comment by d3xter-lab** [comment]
제공해주신 링크 접근해보았으나 동일한 에러가 발생하지 않아서요. 추후 다시 확인되면 이슈 재오픈하겠습니다. 사용중에 다른 오류사항이 있으면 알려주세요~
